### ISSUE TITLE
Width and height problems

### ISSUE THREAD

**Issue by lookingdown** [sampotts/plyr#1100]
Fantastic Player... Thanks .. !
Is there a way to set width and height styling the video 
like so `<video style="width: 320px; height: 240px;" class="plyr-player" controls>`
Tried object-fit: contain; background-size: contain; no luck.. so far
Dont want a container element if it can be avoided as videos generated dynamically, various videos on same page with different sizes.
### Expected behaviour
Size of video according to style directive,  for example `style="width: 320px; height: 240px;"`
### Actual behaviour
Fills available space 100% of width with black background and video in the middle according to style 
--
SIZE STYLING WORKS **IF**  video element enclosed  in `<div class="row"></div>` size style respected and all OK.. but that **dont work** from a layout perspective.. need to apply style inside `<video>` element OR instruction on how to make Plyr respect inline style size directive

### Environment

HTML framework Bootstrap 4.1

- Browser: Chrome latest 
- Version: 67.0.3396.99 
- Operating System: Windows
- Version: 10

### Steps to reproduce
insert style directive inside video element`<video style="width: 320px; height: 240px;" class="plyr-player" controls>` NOT within `<div class="row"></row>`
Then the same within `<div class="row"></row>`
Completely different behaiviour
Cheers

**Comment by friday** [comment]
Use a container outside the video element or set the width. Don't set height unless you want to stretch the video.

**Comment by lookingdown** [comment]
The question was how to style the video element to adhere to size.. the use of an Outside container... is not an option for me for various reason..  Other video players just declare width and height inside the video element and youre done... 
Your answer is in fact that it is NOT possible to size the video element itself in Plyr..  without resorting to outside container.. thats a bummer :(  for my user case... /Thanks

"Is there a way to set width and height styling the video
like so <video style="width: 320px; height: 240px;" class="plyr-player" controls>
Tried object-fit: contain; background-size: contain; no luck.. so far
Dont want a container element "

**Comment by friday** [comment]
This place isn't for support, as stated in our community guidelines that you should have seen before creating this issue. 

Since Plyr is wrapping the video element and needs to do so to add custom controls, captions and poster, the outer container determines the size and the other element adapt. Setting only the video size would only affect the video, not the other elements, and end up looking broken when the video doesnt stretch the whole way. In addition, if the video element has a fixed size, it would stay that way when you fullscreen it.

If anything, style the container (created by Plyr) and make sure it doesn't break fullscreen mode. It's not impossible.

Also. This is CSS. If you want to change how it works by overriding the behavior, nothing is stopping you.
