### ISSUE TITLE
player.fullscreen.enter() - Cannot set property 'pressed' of undefined

### ISSUE THREAD

**Issue by minlare** [sampotts/plyr#1102]
Error in console on Chrome 67
`Cannot set property 'pressed' of undefined`

### Expected behaviour
The fullscreen mode is toggled.

### Actual behaviour
The fullscreen mode is toggled but there is an error in the console.

### Environment
- Browser: Chrome
- Version: 67
- Operating System: Windows 10

### Steps to reproduce
Go to https://codepen.io/minlare/pen/EpKJZW and click the "Start Video" button with the console open.

**Comment by friday** [comment]
Thanks for following our replication instructions :)

With your example `player.fullscreen.enter();` is called just after creating Plyr, and the fullscreen button isn't created in time. This triggers an error, and the fullscreen button doesn't get the right icon and tooltip.

With other methods it's possible to delay until the ui is ready using the `ready`-event, but for fullscreen this isn't possible. Fullscreen must be triggered with a "gesture", so you can't use that event listener.

I agree with you that this shouldn't happen. The UI should not be required in order to change the state. Optimally I think it should be a function of the state (like react components).

The issue as it's replicated could be avoided by pre-rendering Plyr hidden, then showing it when you press the button.
