### ISSUE TITLE
Use player with htpasswd protected file

### ISSUE THREAD

**Issue by manuelvita96** [sampotts/plyr#1117]
Hi everyone, I want to use this amazing player with my video folder that are protected with htpasswd file. If i try to link video with "user:pwd@example.com/video.mp4" I see the login form, how I can play videos with autologin?

**Comment by friday** [comment]
I think you need to add a protocol (like https) making the link `https://user:pwd@example.com/video.mp4`. If this doesn't work, find out what does.

Either way, this has nothing to do with Plyr. You'd get it with native HTML5 video too, and password protecting a file in order to use the password in the code later isn't really secure. You may want to look at streaming libraries and DRM.

https://github.com/sampotts/plyr/blob/master/CONTRIBUTING.md#reporting-issues
