### ISSUE TITLE
Custom Video Endscreen for Vimeo

### ISSUE THREAD

**Issue by nchan9** [sampotts/plyr#1130]
At the end of Vimeo videos, there is an end screen with "Staff Picks." Vimeo currently does not allow users to remove this end card without subscribing. Since Plyr customizes the entire video player design, I feel it would be appropriate to include a feature that removes/allows for customization of the end card to fully customize the player experience.

**Comment by sampotts** [comment]
If it's possible to do via their API/options then we can, otherwise SOL unfortunately 😢

**Comment by friday** [comment]
That's what I already said in Slack ^

There doesn't seem like there is any such option (expectedly since they don't seem to want you to disable this): https://github.com/vimeo/player.js#embed-options

If someone finds a way to do this (preferably not a hack) feel welcome to comment or open a new issue, but otherwise not.
