### ISSUE TITLE
Captions position mismatch on various control schemes

### ISSUE THREAD

**Issue by mjfwebb** [sampotts/plyr#1137]
### Expected behaviour

Captions remain in the same position when no controls are shown (they could be auto-hidden), regardless of controls being configured or not.

### Actual behaviour
Captions are shown in different positions (y-axis) when controls are hidden versus when no controls are configured.

### Steps to reproduce
Configure a player with only `controls: ['play-large']` or `controls: []`

### Link to where the bug is happening

https://codepen.io/mjfwebb/pen/PBEaRY
(Should autoplay if you have vimeo muted. If not, load the codepen then refresh after a couple of seconds.)

**Comment by friday** [comment]
Thanks! This actually shows three separate problems.

1. The first and second video position captions differently.
2. The third example shows a similar bug with `null` added to the output that was fixed in #868.
3. The third example has no controls element at all. The css we added is applied for captions *after* empty controls, but not after "no controls". So the css should be changed.

#1139 should fix 2-3 (not verified with your example though).

This can be used to fix 1:

```css
.plyr--hide-controls .plyr__captions {
 transform: translateY(0);
}
```

**Comment by friday** [comment]
This is fixed now (but not released yet). I made a temporary build to test with your pen. If you want, you can verify it by changing the external references in your pen's settings to:
https://rawgit.com/friday/plyr/1137-build/dist/plyr.min.js
https://rawgit.com/friday/plyr/1137-build/dist/plyr.css

**Comment by mjfwebb** [comment]
Agreed, I updated the pen and it's working excellently now. Thanks @friday
