### ISSUE TITLE
Preroll or intro

### ISSUE THREAD

**Issue by nexushp** [sampotts/plyr#1243]
Hi! I'm starting to use this player on my new website, is so much easier to use and control! So fast and clean! But I want a "preroll" on my website... I mean, a **.mp4** file plays before the media starts.

**Comment by musicworldcup** [comment]
Hi,
  I signed up in VI and get the publisher id. configured in player
 Still ad not showing in player.
 In VI dashboard number of request is 0.
Here is my code 
data-plyr-config=' {"debug": true, "title":"Test", "ads":true, "publisherId":902676586493663 } '

**Comment by sampotts** [comment]
@musicworldcup Your question is unrelated to this one. Your issue is your config is incorrect. The `ads` property value is an object, also publisher ID is a string. So your example should be `data-plyr-config=' {"debug": true, "title":"Test", "ads": { "enabled": false, "publisherId": "902676586493663" } } '`

@nexushp Sorry this isn't possible with anything built-in. Ads are currently all managed through the Vi ad plugin.
