### ISSUE TITLE
The First of my Plyr Players on Bootstrap Tab Works but the Second one does not Work

### ISSUE THREAD

**Issue by Reqrefusion** [sampotts/plyr#1336]
I use bootstrap tabs in my projekt. There will be player on each of them which tab content but secon one html5 player. This is odd because i use very basic code. And you can see my codepen example.

https://codepen.io/turan-furkan-topak/pen/ompBrX

You can see my problem if you click on Video2 tab in example.

**Comment by sampotts** [comment]
Hey,

As per [the docs](https://github.com/sampotts/plyr/#setting-up-multiple-players), you need to set up each player individually or use the static `Plyr.setup` method and pass as selector to it. Otherwise you're using the Constructor which will only setup one player (since it's a class). 

Here you go:
https://codepen.io/sampotts/pen/KJZZMx

Note: Plyr.setup will return an array of players it sets up. If you want better control over reference to the players. You can always add an id on the elements and loop or something:

```javascript
const players = {};

Array.from(document.querySelectorAll('video')).forEach(video => {
    players[video.id] = new Plyr(video, { ...options });
});
```

**Comment by sampotts** [comment]
Updated the comment for others in future to find it easier.

**Comment by HybridSolutions** [comment]
The instructions are not very clear for multiple instances. 
You have  `const player = new Plyr(document.querySelectorAll('.js-player'));` but this will not apply the player to all the instances, and i believe that's why there's some confusion.

Also, you don't show how to specify options when using `const players = Plyr.setup('.js-player');` in the instructions.
These issues should be improved for clear understanting on how the player works..

**Comment by sampotts** [comment]
I’ll make a change to the docs

**Comment by EndiHariadi43** [comment]
Maybe you want to see what I have done? https://codepen.io/anon/pen/gZYEme

**Comment by ankevaneijk1** [comment]
> 
> 
> Hey,
> 
> As per [the docs](https://github.com/sampotts/plyr/#setting-up-multiple-players), you need to set up each player individually or use the static `Plyr.setup` method and pass as selector to it. Otherwise you're using the Constructor which will only setup one player (since it's a class).
> 
> Here you go:
> https://codepen.io/sampotts/pen/KJZZMx
> 
> Note: `Plyr.setup` will return an array of players it sets up. If you want better control over reference to the players. You can always add an id on the elements and loop or something:
> 
> ```js
> const players = {};
> 
> Array.from(document.querySelectorAll('video')).forEach(video => {
>     players[video.id] = new Plyr(video, { ...options });
> });
> ```

In your codepen, when you start playing one video and then open another tab, the first video continues to play in the background. How can you stop the other video when opening another tab?
