### ISSUE TITLE
If unmuted plyr not working

### ISSUE THREAD

**Issue by kayef1436** [sampotts/plyr#1431]
When I am using 
`const player = new Plyr('#player', {autoplay: true, muted: true, volume: 0});`  video plays. But if I am using `const player = new Plyr({autoplay:true,volume:1});` its not playing. Kindly help me to solve the issue

**Comment by sampotts** [comment]
Use the first one then if it works? You need to pass a selector, element, node list or array to the constructor as per the docs.

**Comment by kayef1436** [comment]
I got the bug. In android webview, when i am muting it plays but when i am unmuting it pauses and not playing.

**Comment by laurensV** [comment]
This problem is also there in chrome on Macs.. Works on windows/linux on chrome, but on mac the video's only play when you mute the video. As soon as you unmute the video it pauses the video and shows the following javascript warning:

> Unmuting failed and the element was paused instead because the user didn't interact with the document before.

**Comment by baderkhane** [comment]
any solution guys for this problem

**Comment by adiwithadidas** [comment]
Is there any solution for this problem. I am getting this same issue.

**Comment by adiwithadidas** [comment]
> This problem is also there in chrome on Macs.. Works on windows/linux on chrome, but on mac the video's only play when you mute the video. As soon as you unmute the video it pauses the video and shows the following javascript warning:
> 
> > Unmuting failed and the element was paused instead because the user didn't interact with the document before.
> 
> Above problem only happens when you are using it in a iframe like codepen/jsfiddle, so to test it you can use this jsfiddle:
> 
> https://jsfiddle.net/b783zmL2/4

Did you find any solution for the same?

**Comment by aneeskhan47** [comment]
Issue: if plyr or any other video player is used in website and video can’t be played by tapping on play ️icon typically it throws the following error in android logcat: play() can only be initiated by a user gesture, source: either it will be vimeo.js or youtube etc

Solution: add webViewSettings.setMediaPlaybackRequiresUserGesture(false); in your android code (where your webview code is)

@adiwithadidas

**Comment by slayybelle** [comment]
I am able to autoplay + mute in chrome on MacOs. The problem starts upon clicking unmute or volume slider, and then I get the console message other posters got "Unmuting failed and the element was paused instead because the user didn't interact with the document before"

Note: React-player also must start out muted for iframe autoplay; once user clicks unmute, video continues to play and you do NOT get the "Unmuting failed..." message.

My guess was the Plyr unmute was not registering to youtube as a "user interaction" so I started searching the element listing in devtools for something that would count as "user interaction" and found this hidden button:
`<button class="ytp-unmute ytp-popup ytp-button ytp-unmute-animated ytp-unmute-shrink" data-layer="2" style="display: none;">`

if I set display to flex and used that button to unmute (instead of the plyr unmute), then the video will play w/o the original "Unmuting failed and..." message, in a similar fashion as I've seen with React-player (start play programmatically, click unmute, keeps playing, no error msg).

There's a lot of unanswered questions though.  Is this a viable solution?  clicking the ytp-unmute doesn't affect plyr state so the plyr unmute button is still in muted state.  Also, I can only interact with ytp-unmute when plyr is paused, which is not ideal.  Not sure why this is the case and if I can work around it somehow
