### ISSUE TITLE
Volume slider broken for youtube plyr - doesn't mute on refresh

### ISSUE THREAD

**Issue by realmichaelye** [sampotts/plyr#1934]
What happens:
- When dragging the volume slider to set volume to 0, it initially works
- however, once you refresh the page / load a different youtube video, the volume still shows it's 0 (with muted icon), however there's still sound playing

How to reproduce bug:
- go on https://plyr.io/#youtube
- drag volume slider to 0
- refresh the page
- play the video

**Comment by sparkktv** [comment]
Just tried it and it stayed muted even after refresh. Had to turn up volume in order to hear. It could be a browser issue but not a Plyr issue. I just tried with Safari and it worked as it's suppose to...

**Comment by stephanefbouchard** [comment]
Confirming that this issue is still happening. 

Seems related to the behavior of youtube that set the volume back to a miminum value of .20 after unmute

Im not pretending this is the right fix at all ! But resetting the volume after unmute solve the problem

<img width="716" alt="Screen Shot 2020-09-28 at 9 28 49 PM" src="https://user-images.githubusercontent.com/1608601/94502312-de0b3080-01d1-11eb-9d75-50e99e936452.png">

**Comment by sampotts** [comment]
The fix for this is in v3.6.3 👍 Thanks!
