### ISSUE TITLE
Pip when scrolling

### ISSUE THREAD

**Issue by epinay1** [sampotts/plyr#2009]
Hi, 
I would like to enable the PIP functionnality while scrolling down my page, but I can't figure out in the plyr.js what function I am supposed to call to activate the PIP from my other js program(that takes care of the scrolling part).
Could somebody please tell me how to do that?

**Comment by sampotts** [comment]
I'm not sure you'd be able to do this programmatically. It's a feature that I would suspect (99% sure) would require user interaction, like entering fullscreen, for obvious reasons. What the news sites often do is create their own kinda psuedo picture in picture but it's relative to the browser viewport rather than the display.

**Comment by epinay1** [comment]
So you don't think there is a way to "simulate" the click on the PIP button?

**Comment by sampotts** [comment]
It can be simulated but it's highly likely it'll just get ignored by the browser and a warning or error shown in the console.

**Comment by epinay1** [comment]
Yes you're right, I've tried it many ways but my browser refuses to let me enter PIP mode without me clicking at least a button.
Thanks anyway.
