### ISSUE TITLE
just a question.

### ISSUE THREAD

**Issue by ubm1** [sampotts/plyr#2050]
Is there a way to deliver "chunks" or parts of the mp3 and mp4, instead of the whole file at one time?

**Comment by souvik362** [comment]
@ubm1  Nice Question 😀

Its known as  **"on-the-fly packaging"** . It means delivering only  the chunks of video that viewers play. so user can start playback immediately instead of waiting for the entire file to be downloaded. its helps to enrich user experience .
This is how YouTube do its smooth playback. 
its mostly a server side (CDN) features. 

This features  offered by
1.  [Fastly CDN](https://www.fastly.com/products/media-and-streaming/video-on-demand)
2.  Cloudinary 
3. You can built this as your own by using some premium CDN provider like akamai, cloudfront etc.

i hope it answer you desired question 🎈

**Comment by ubm1** [comment]
@souvik362 How do you implement that with plyr? I know that you can use dash.js and shaka.js for doing that, but that's a lot more complex with different bitrates switching between versions using DASH and HLS, but thats a little more robust then what I need. I just want to deliver chucks to the plyr library, but don't see any documentation on how to do that.

**Comment by ubm1** [comment]
I basically have a website that has a ton of videos and audio files. When I put my website into production I noticed my videos ranging from 1-2 hours long would take the video  77 seconds for the video to start playing. I started  researching why, and found that my MOOV index on the video was appearing in the back of file rather then front so I changed it (very old videos). After that happened the video started playing right away Now I have a new issue. When the user seeks to a new location, it still takes a unreasonable amount of time for it start playing again. What would be the best solution for this? I know I can use dash.js and shaka.js, but that seems like a lot of work for a solution.  What should I do? I appreciate all the help if anyone can help thank you.

**Comment by souvik362** [comment]
@ubm1 I came after this  [blog post by cloudinary](https://cloudinary.com/blog/html5_video_tags_won_t_do_for_your_videos)
Cloudinary has their own video player to do this type of things which use videos.js

But if you want to use plyr with adaptive video streaming then I would refer you to  use YouTube embed to do this

**Comment by ubm1** [comment]
@souvik362 ok man I will take a look thanks for the reply!
