### ISSUE TITLE
Plyr does not rescale YouTube/ vimeo videos in full screen when the screen height decreases

### ISSUE THREAD

**Issue by calvintam236** [sampotts/plyr#222]
When plyr is playing YT/vimeo video in fullscreen, and screen heigh decreases, the video itself does not rescale. Tested and confirmed on Firefox & Chrome.

Expected (regular video):
![screen shot 2016-05-17 at 2 38 47 pm](https://cloud.githubusercontent.com/assets/6436149/15340205/1f27445c-1c3d-11e6-9158-6d3127d50d7d.png)

YouTube/ Vimeo videos:
![screen shot 2016-05-17 at 2 40 02 pm](https://cloud.githubusercontent.com/assets/6436149/15340245/48aaacba-1c3d-11e6-9aea-7ba6355c03ab.png)

**Comment by SamPotts** [comment]
Will take a look, cheers 👍

**Comment by frumbert** [comment]
I see the same except without full screen. when the body is at a ratio wider than 16:9, the player controls and video both slip off the bottom of my viewable surface. In my code the plyr is in a div as a child of the body, like so

    <body>
        <div data-video-id="12345" data-type="vimeo"></div>
    </body>

and I've styled body, html to be full view height:

    html, body { height: 100vh; overflow:hidden; }

In my case I had to add a height hack

   .plyr .plyr__video-embed iframe { max-height: 100vh; }

so that neither the player controls nor the underlying natural embed can grow higher than this. I'm still also trying to figure out a suitable workaround for the undocumented soundcloud player

**Comment by frumbert** [comment]
plyr v2.0.17, Youtube full screen, Windows 7

![image](https://user-images.githubusercontent.com/592257/34248747-4340013e-e68b-11e7-89c5-a457a68e0b9f.png)

**Comment by sampotts** [comment]
Do you see this on https://plyr.io? What browser? 

I see you deleted the template which helps me debug these issues 👎

**Comment by sampotts** [comment]
I'm not able to replicate the above... I'd say you have a CSS issue there

**Comment by sampotts** [comment]
Closing this one as I think it's fixed but feel free to re-open if not solved in v3 👍

**Comment by calvintam236** [comment]
@sampotts FYI: reopening the issue is not an option even for me (issue author). I will check on the code later this week and report back.
