### ISSUE TITLE
plyr.js is 110KB big for a video player?

### ISSUE THREAD

**Issue by kw005** [sampotts/plyr#2554]
HI, I am new to Plyr. The Play is probably my favorite comparing to many other players. 

However, I am wondering how to use it, via CDN? But the JS file alone is 
110KB big - that is correct or is there any other "smaller/more efficient" way of using Plyr?

Thanks

**Comment by sampotts** [comment]
The current (v3.7.2) minified and gzipped sizes are:
- [JavaScript](https://unpkg.com/plyr@3.7.2/dist/plyr.min.js) - 33.69KB
- [CSS](https://unpkg.com/plyr@3.7.2/dist/plyr.css) - 5.81KB
- [SVG Sprite](https://unpkg.com/plyr@3.7.2/dist/plyr.svg) - 2.08KB
A total of 41.58KB. This can potentially be reduced when included in your own bundles and they gzip down further.

The problem is that currently, the distributed code is "all or nothing", meaning there's no way to opt out of certain features or plugins. We'll address this in the next major version as part of Vidstack.

**Comment by kw005** [comment]
Hi sampotts,
Thanks for replying so fast. How can I do my own bundles? Is there a guide for doing it?
Thanks

**Comment by Colir** [comment]
Hi, I'm also interested in doing my own bundles. Is there any guide on this?
Thank you
