### ISSUE TITLE
Bundle the minified versions

### ISSUE THREAD

**Issue by timint** [sampotts/plyr#2637]
I was not able to find any minified versions. I couldn't build my own since the project was not compatible with Node v18 or Node v19 and no compatible Node version is specified.

A suggestion to embed a dist/ directory in the root with compiled web versions like plyr.min.js and plyr.min.css. So everyone doesn't have to go through the trouble of installing and initiating 400 MBytes of libraries just to compile web versions of this thingy.

**Comment by sampotts** [comment]
As discussed on plenty of occasions, including the built code isn't realistic and makes pull requests a nightmare since everyone included their versions of the built source. You'll notice the majority of projects also don't include built files for this reason. 

There are plenty of ways to build it yourself, one of which being build it yourself in isolation as you've found, but this obviously means downloading all the dependencies etc. Again, a standard thing you'll find with similar packages. It's the nature of the beast. The other of course is one you'd have found by searching issues, using unpkg or similar:
https://github.com/sampotts/plyr/discussions/2094

**Comment by sampotts** [comment]
I'll highlight this in the doc. You can also just download the files from the CDN directly, which are minified:
https://github.com/sampotts/plyr#javascript
