### ISSUE TITLE
How do you manage mutli sound track ?

### ISSUE THREAD

**Issue by IPTVelum** [sampotts/plyr#2756]
Hello everyone,

I'm facing a problem with Plyr and my app, some of the videos I use come from the web and I have no control over them.

Some videos are in MKV or MP4 format, and I think because of the multiple sound tracks in them, there is no sound at all.

Is there anything you've already seen?

Thank you 🙏

**Comment by alexpado** [comment]
I don't know if you figured something out since, but having multiple sound tracks should not cause issues at all. I think the issue might be the audio codec used for the audio; webbrowsers do not support a lot of them.

If it is DTS, you can check this compatibility table:
https://developer.dolby.com/platforms/html5/browser-support/

For other format, I suggest taking a look to this:
https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Audio_codecs

You can check the codec used with different tools, like mkvmerge (from mkvtoolnix) or even vlc
