### ISSUE TITLE
youtube/vimeo in a fixed-height iframe; need to be able to initialise with a set height

### ISSUE THREAD

**Issue by frumbert** [sampotts/plyr#371]
If I have my player in an iframe that has a fixed height but a percentage width (e.g. 100%) then the player can be initialised with controls that are off the bottom of the screen. Since the aspect ratio is maintained, controls could be quite far below the position of the bottom of the iframe.

If I set in my css

```
.plyr, .plyr .plyr__video-embed iframe { max-height: 100vh; }
```

so that the plyr instance and its embedded video (youtube, etc) are both only as high as the height of the visible window (in that case, the iframe itself) then the aspect ratio problem is solved since the height can't be higher than the container.

It would be great to be able to specify the max-height during `setup()`, since in my use cases I sometimes know the maximum height I have to spend...

**Comment by SamPotts** [comment]
Setting the height with JavaScript isn't something I'm keen on. That should really be kept in CSS but I'll have a think about it...

**Comment by AlGantori** [comment]
Any fix for this? I have rewrote my CSS with a single div wrapper with the following CSS (your guidance is much appreciated)
```
// https://github.com/sampotts/plyr/issues/371
// https://stackoverflow.com/questions/35176745/i-think-google-chrome-for-android-has-a-bizarre-viewport-height-error-and-it-sh
// 20180413
.PlyrVideo_Container {
    position: absolute;
    top: 0;  
    //
    width: 90vw;  
    height: 100vh !important; // this is getting ignored ???
    // display: flex;
    // align-items: stretch;
    // justify-content: space-around;  

            @media all and (orientation:portrait) {
                top: 10vh;
                width: 100vw;
            }
}
```
my HTML template looks exactly like this:
```
<!-- 20180413 -->
<div class="PlyrVideo_Container">
    <!-- v3.1.0 suggested using this div as the "progressive enhancement" -->
    <div class="plyr__video-embed"
        id="plyrjs">
        <iframe src="https://www.youtube.com/embed/?origin=https://plyr.io&amp;iv_load_policy=3&amp;modestbranding=1&amp;playsinline=1&amp;showinfo=0&amp;rel=0&amp;enablejsapi=1"
    
            allowfullscreen
            allowtransparency
            allow="autoplay"></iframe>
    </div>
</div>
```
I don't have an issue with portrait because I do set the container's width.  **In landscape I would like to set the height**. However, the player does not seem respond to the above height: 100vh setting no response either if I set the container to 80vh.  Why is that?
The problem is very visible when I am running in chrome on the Android device.
Here is a snapshot
![image](https://user-images.githubusercontent.com/11699920/38764256-9a4d3dba-3f60-11e8-85e2-073853eec2ec.png)

On Windows chrome it's not reproducible, here are the rendering for a Galaxy S5 for example:
![image](https://user-images.githubusercontent.com/11699920/38764214-bb0fa5c0-3f5f-11e8-8f11-2cc3baee8ffd.png)

![image](https://user-images.githubusercontent.com/11699920/38764222-d8068dce-3f5f-11e8-9f97-4247fae0246c.png)

https://stackoverflow.com/questions/35176745/i-think-google-chrome-for-android-has-a-bizarre-viewport-height-error-and-it-sh
I stumbled on this older issue of chrome on Android and its viewport which apparently was release many revision back (M56 in 2016) my Android Chrome version is 65.xxxx

I don't know what to do next.
I was able to integrate with 3.1.0 just yesterday after being stuck on 1.8.12 for too long.
The issue setting the height being ignored remains.
Thanks for a great player.

**Comment by sampotts** [comment]
Can you try the latest version? I think this is resolved now. Please report back if not.
