### ISSUE TITLE
Annotations on for Youtube

### ISSUE THREAD

**Issue by ImranBug** [sampotts/plyr#383]
Thanks for the great plugin!!
Can you please guide me how can I turn on Annotations for you-tube player or add this functionality if it doesn't exist.

Thanks,
Imran.

**Comment by SamPotts** [comment]
Good suggestion. I'll add this to the list. 👍

**Comment by mysticdrew** [comment]
Any updates on this? We are looking to use some youtube videos on our site but we need captions. If we use raw youtube the captions are too small with our smallish window. Readable captions are needed for 508. I was hoping to use plyr.io but without captions we will have to go another route, unless something changes soonish. 

Thanks!

**Comment by gfreedncam** [comment]
I would like to verify that if I use Plyr to play captioned YouTube-hosted videos, Plyr *will*, in fact, surface a CC button so viewers will be able to toggle the YT captions on and off from within the Plyr UI.  Is this true?  

Thank you.

**Comment by tlexcellent** [comment]
Still no update ? https://ableplayer.github.io/ableplayer/ can do it, but Plyr is really more elegant.

**Comment by friday** [comment]
I created a new issue #1090 for subtitles (captions), so for further discussion about that please go there.

This issue seems to actually be about *annotations*, which is not the same thing. In addition [annotations have been removed from YouTube](https://www.tubefilter.com/2017/03/17/youtube-phase-out-annotations-cards-end-screens/) (but is still supported for old videos).

**Comment by friday** [comment]
> I would like to verify that if I use Plyr to play captioned YouTube-hosted videos, Plyr *will*, in fact, surface a CC button so viewers will be able to toggle the YT captions on and off from within the Plyr UI.  Is this true?  

No. This is not supported.

**Comment by andyhu** [comment]
> > I would like to verify that if I use Plyr to play captioned YouTube-hosted videos, Plyr _will_, in fact, surface a CC button so viewers will be able to toggle the YT captions on and off from within the Plyr UI.  Is this true?
> 
> No. This is not supported.

Will it be supported in the future?

**Comment by friday** [comment]
I'm taking the liberty of closing this, since it's almost entirely off topic. The topic is adding support for is a YouTube-specific feature which they have now abandoned. I doubt anyone is interested in developing or supporting this.

If you found this you're probably interested in #1090 rather than annotations.
