### ISSUE TITLE
Audio of videos does not stop when video is paused or muted

### ISSUE THREAD

**Issue by tanvan81** [sampotts/plyr#399]
Sometime, I've trouble:

I've  muted but audio still playing

First, I muted audio. Then press F5 to refresh, the video is load with controls muted. But audio still playing

**Comment by SamPotts** [comment]
Please provide some more information for debugging:
- Browser (e.g. Chrome 54)
- Platform (e.g. Windows 10, MacOS Sierra)
- Video type (HTML5, YouTube or Vimeo)

Remember Plyr is purely an abstraction for all HTML5 and embedded iframe players so most issues like this are caused by the media itself or are a browser related bug. Plyr does not have independent control over Audio and Video. It just uses the browser or 3rd party APIs.

**Comment by tanvan81** [comment]
I've test on chrome and FF on win 10

here url 

https://jsfiddle.net/cceLroom/4/

First' I've mutes and then refresh, so Audio still not playing

**Comment by SamPotts** [comment]
Seems to be a new bug related to autoplay. I'll take a look. Thanks for reporting.

**Comment by tanvan81** [comment]
and sometimes, I've trouble

When I press pause video, I still hear audio

**Comment by SamPotts** [comment]
Yep, as above - looks to be a browser autoplay issue. I'll take a look.

**Comment by tanvan81** [comment]
Hey, 

I've remove property "autoplay" on video html5, that's ok. And when call setup(), I call play().

**Comment by jarcarlos** [comment]
Work fine in MS Edge, but in Firefox and Chrome, when we pause video, the audio still working...
