### ISSUE TITLE
Plyr and svg4everybody fighting on Internet Explore (Tested IE 10 and IE 11 )

### ISSUE THREAD

**Issue by joshuapease** [sampotts/plyr#407]
I'm noticing that Plyr's SVG icons wont display whenever I use [svg4everybody](https://github.com/jonathantneal/svg4everybody) on my projects.

Right now I've been letting the default CDN version of the icons load. 

http://codepen.io/joshuapease/pen/xENeNQ

When SVG4Everybody is in use, Plyrs icons just end up as an empty <svg> tag

**Comment by SamPotts** [comment]
Hmm strange one. I've never had to use svg4everybody before as I just load sprites separately and reference them using the `<use>` element. I'd have to have a play. Is there an option to ignore certain `svg` elements?

**Comment by joshuapease** [comment]
Hmm, none that I'm aware of. 

I ended up using the SVG loading method you [described in the readme](https://css-tricks.com/ajaxing-svg-sprite/). It's a good workaround. 

It was a little tough for me to figure out why the icons weren't working at first. But I don't think there's anything you need to do on your end. 

This issue might be good for people to be aware of. I'll contact svg4everybody and see if there's any workarounds.

**Comment by Quirksmode** [comment]
I am having the exact same problem :-(

**Comment by yunusga** [comment]
http://codepen.io/anon/pen/ggadeK
demo with custom SVG-sprite all work fine in ie 11 (with and without SVG4Everybody), not tesed in IE 10 (codepen not working with emulated IE 10), but i have [screen](http://i.imgur.com/DtWCVD4.jpg) from local project in IE 10, all works fine only with [custom sprite](http://codepen.io/anon/pen/ggadeK), default SVG-sprite not work

**Comment by SamPotts** [comment]
Perhaps raise the issue here:
https://github.com/jonathantneal/svg4everybody/issues

**Comment by brandon-pereira** [comment]
Hey guys,

I think I found a fix for this. There are 2 issues:

1.  You need to disable the loadSprite boolean in your options "{loadSprite: false}" to disable messing up non-video related svgs on your page
2. IE is currently always loading external URLs.. but because svg4everybody is making these svgs locally available Plyr is messing up by trying to load the external URL.. I've created a pull request to disable this.. see its status here: https://github.com/Selz/plyr/pull/577
