### ISSUE TITLE
Bugs with UI elements when used with Magnific Popup

### ISSUE THREAD

**Issue by shainanigans** [sampotts/plyr#495]
Hi there,

I'm having some issues using plyr with Vimeo and YouTube vids inside of a popup (using [Magnific Popup](https://github.com/dimsemenov/Magnific-Popup)). 

See my [codepen](http://codepen.io/shainanigans-1472169587/pen/ygERqP) for a reduced test case.

Issue does not already exist, cannot be observed on https://plyr.io

### Expected behaviour 
On play, play button should disappear and progress should appear on progress bar. Class `plyr--playing` should be added to `div.plyr` while `plyr--stopped` should be removed.

### Actual behaviour
Play button remains visible while video is playing, progress is not shown on progress bar. Class `plyr--playing` is never added while `plyr--stopped` is never removed.

### Environment

- Browser: all
- Version:  all
- Operating System: all
- Version: all

Players affected:
- YouTube
- Vimeo

### Steps to reproduce 
- See [codepen](http://codepen.io/shainanigans-1472169587/pen/ygERqP)

**Comment by danieliser** [comment]
I am getting this same thing with my popup plugin Popup Maker. Sometimes the play button fades out properly but often it doesn't.

I was able to fix it by adding an event listener to the 'play' & 'progress' events and adding the classes if missing.

Another thing I have noticed and it may be related is that when we try to seek() or rewind() prior to playing on popup open the progress slider breaks. That is to say it doesn't move while playing.

Not sure but it may be related to elements being hidden when initialized or because items are hidden when pause is run etc.

**Comment by frumbert** [comment]
I found that if the player is initialised on a dom node _and then_ that dom node is moved (say, to a modal overlay), the player still works _but_ listeners for the play/pause/ended functions no longer fire, and it's the fact that the node has moved away from where it was initialised that causes the `plyr--stopped` and `plyr--playing` to stop getting applied to the container.

I found this out by first initialising the playing the player, then moving it to a different node when the user began a navigation event that re-pulled content to the page - I had wanted to keep the video playing whilst that navigation loaded and the elements around the video changed.

That seems to be what is going on in this pen as well - the plyr is initialised THEN the modal is created and the video element is put into it. When it's html5, it doesn't seem to be a problem since I guess the way it initialises and holds reference to those events/nodes?

**Comment by wesleymacente** [comment]
Try This:

// external js:
// jquery
// plyr
// magnific popup

// initialise  plyr


// initialise magnific popup
$(".container").magnificPopup({
  delegate: ".btn",
  type: "inline",
  gallery: {
    enabled: true
  },
  callbacks: {
    updateStatus: function(data) {
      if (data.status === "ready") {
        window.dispatchEvent(new Event("resize"));
      }
    },
    resize: function() {
      plyr.setup(".jsMediaPlayer");
    }
  }
});

**Comment by benrosati** [comment]
You'll want to create and destroy for every mfp open and close event. 

`$.magnificPopup.open({
      items: {
        src: '#pop',
        type: 'inline'
      },
      removalDelay: 500,
      mainClass: 'mfp-zoom-in',
      callbacks: {
        open: function(){

          players = plyr.setup('.js-player', {
            autoplay: true,
            controls: ['progress', 'current-time', 'mute', 'volume', 'fullscreen']
          });

        },
        close: function(){
          players[0].pause();
          players[0].destroy();
        }
      }
    });`
