### ISSUE TITLE
Is there a way to Autoplay on the subsequent movies?

### ISSUE THREAD

**Issue by AlGantori** [sampotts/plyr#507]
It looks like on the mobile devices Android and iOS and unlike Windows desktop browser, when I initiate a YouTube video the user is expected to press manually the play button presented on top of the player.
Is there a way to circumvent this limitation on subsequent playback?

I cannot pre-build a playlist of movies because my playlists have mixed media by design, which the PlayersController need to schedule for the correct sequencing.  The user also can go forward and backwards into the playlists switching from a movie to a slideshow to etc....

I am managing to keep a single instance of plyr is there a way to feed it the next video id without requiring user intervention?
I somewhat understand the limitation imposed on the first movie for security / UX issues.
is the limitations built in the YouTube API you must be using?

I am currently using the following code to play movies feel free to suggest otherwise..

```
 // 20160804
  PlayVideoByID(VideoID) {
    setTimeout(() => {     // timeout to circumvent some recent/current race condition at startup.
      // -- setup NEW sourceS
      if (typeof this.Player !== 'undefined')
        // if (this.Player !== null)
        this.Player.source(
          {
            type: 'video',
            title: 'Example title',
            sources: [
              {
                src: VideoID,
                type: 'youtube'
              }
            ]
          });
    }, 1000);
  }
```

Thank you.

**Update:**
I have posted to the youtube-ifram-api which I believe you must be using.  The plyr doc still points to the deprecated page for embeds.

http://stackoverflow.com/questions/42217929/is-there-way-to-autoplay-on-the-subsequent-movies-youtube

**Comment by friday** [comment]
It should be possible to loads content of mixed sources and use the `ended` event to detect when you need to load the new source. Due to the browser autoplay restrictions you mention (which is worse by now) you probably want to avoid autoplay or mute the audio. There is no other feasible way around it. I think you should then be able to run the code that handles the whole "queue" of videos, but you may need to create your own click handler or something.

This has everything to do with html5 media and browsers. Plyr is just a layer on top and doesn't set these restrictions, so I'm closing the issue. If you have further questions please go to the slack channel: https://bit.ly/plyr-chat
