### ISSUE TITLE
Error event not fired

### ISSUE THREAD

**Issue by Skwai** [sampotts/plyr#508]
Compare native error with plyr implimentation.

http://codepen.io/Skwai/pen/ygZVLq

The `player.on('error', ...)` event isn't fired for a source that 404s

**Comment by yuriykuzin** [comment]
I want to add... In case when I try to open video which was deleted, I see the different behavior for youtube and vimeo:

youtube: `player.on('error', ...)` is fired
vimeo: `player.on('error', ...)` is NOT fired, but exception in promise is thrown

**Expected behavior:** 
Fired error event with the same error code for youtube and vimeo, if video is unavailable. No error exception is thrown

**Browser and OS:**
Chrome 61.0.3163.100 (Official Build) (64-bit), macOS SIerra 10.12.6 (16G29)

**Comment by sampotts** [comment]
Closing this one as I think it's fixed but feel free to re-open if not solved in v3 👍

**Comment by liquidvisual** [comment]
I'm not able to get this working in v3
 
404s don't seem to be triggering errors. Am I doing anything wrong?

```
this.playerInstance.on('error', (event) => {
                console.log('ERROR: '+event)
            });
```

**Comment by ahu** [comment]
me too.

**Comment by Geeta-Singh** [comment]
I'm facing the same issue but it is inconsistent .

**Comment by sukhwinder-somar** [comment]
still seems to be existed, with 403 and 404
