### ISSUE TITLE
Play Video using .play() on mobile not working

### ISSUE THREAD

**Issue by baberuth22** [sampotts/plyr#589]
### Expected behaviour 

Video Plays

### Actual behaviour

Spinner spins

### Environment

- Browser: Chrome
- Version:  
- Operating System:  iOS
- Version: 10.0.2

Players affected:
- [x] HTML5 Video
- [x] HTML5 Audio
- [x] YouTube
- [x] Vimeo

**Comment by mgambati** [comment]
Up. Same happening here.

**Comment by RicardoGeek** [comment]
happening for audio as well :(

**Comment by ferdiemmen** [comment]
Related: https://developers.google.com/youtube/iframe_api_reference#Mobile_considerations

**Comment by brianberneker** [comment]
Sorry I can't post an example due to my working arrangement, but I have found the same problem.
When I embed a vimeo video using the vimeo player, I can get it to autoplay on desktop, or autoplay with volume set to 0 on mobile (mobile allows autoplay on silent).  With plyr, I get a "playing" event, but the video doesn't play?  Has anyone been able to get around this?

My next attempt will be to instantiate the video with plyr, but control it with the vimeo.

By the way, I love plyr, but the docs could be a bit more complete.
For example, the jsFiddle example uses:

 var instances = plyr.setup({
    // Output to console
    debug: true
  });

But the docs don't mention plyr.setup at all, instead documenting usage this way:

const player = new Plyr('#player', {
    /* options */
});

This makes it harder to debug the above problem because I'm trying to find the vimeo API equivalent to autoplay allow parameter (which might be causing my player not to start), or how to use plyr's API to access it.

**Comment by friday** [comment]
Closing, since this is an intended limitation of some browsers with scripted play as well as autoplay. See Ferdi's comment: https://github.com/sampotts/plyr/issues/589#issuecomment-310333452

Muting the audio should work, as well as triggering `play()` from an event listener for certain events such as touch events.

**Comment by friday** [comment]
@brianberneker The only outdated links should be the codepen examples for streaming. Plyr used that syntax before v3. I agree they should be updated to avoid confusion.
