### ISSUE TITLE
iOS: 'playing' and 'ended' events don't fire from Plyr instance

### ISSUE THREAD

**Issue by jvlahos** [sampotts/plyr#651]
- [x] Issue does not already exist
- [ ] Unable to observe issue on https://plyr.io due to no events in console on iOS

### Environment
- Browser: Safari
- Version:  10.1
- Operating System: iOS (Simulator)
- Version: 10.x

### Expected behaviour 
Across browsers/devices:
- When the video begins to play (either for the first time, after having been paused, or after ending and then restarting), the `playing` event should fire.
- When playback completes, the `ended` event should fire.

### Actual behaviour
- In Safari on iOS, the `playing` or `ended` events do not fire when using the Plyr instance. However, they do fire correctly when using the `<video>` element.
- On Chrome or Safari on OSX, the `playing` or `ended` events fire correctly when using the Plyr instance.

Players affected:
- [x] HTML5 Video
- [ ] HTML5 Audio (not tested)
- [ ] YouTube (not tested)
- [ ] Vimeo (not tested)

### Steps to reproduce 

```js

// 1. Test this on iOS. Events do not appear in console.

var instance = plyr.setup('video')[0];

instance.on('playing', function(){
  console.log('playing');
});

instance.on('ended', function(){
  console.log('ended');
});

// 2. Then test this on iOS. Events appear in console. 

// jQuery example
var $videoElement = $('video');

$videoElement.on('playing', function(){
  console.log('playing');
});

$videoElement.on('ended', function(){
  console.log('ended');
});

```

### Relevant links
* https://developer.mozilla.org/en-US/docs/Web/Guide/Events/Media_events

**Comment by baseten** [comment]
This happens with the Vimeo player too. 

Loading the below page via iOS simulator it is clear that these events are supported by the native player:

https://www.w3.org/2010/05/video/mediaevents.html

**Comment by baseten** [comment]
I'm finding that removing the check for `!isIos` for vimeo is working without issue (at least in iOS simulator for iPhone 7 iOS 10.2).

I remember the issue with programmatically calling play was always to do with whether the `play` call originated from a user touch event or some random code. I'm not sure if this is still officially the case, but it appears to work fine when clicking on an external button to trigger `play`.

**Comment by ashleahhill** [comment]
I'm assuming this is for v2 because of the date. In v2 when plyr is not fully supported the interface isn't completely setup. iPhone is one of the cases where plyr is not fully supported. 

Here you can see that `_setupInterface` bails before the media events are bound: https://github.com/sampotts/plyr/blob/master/src/js/plyr.js#L3539.
And here: https://github.com/sampotts/plyr/blob/master/src/js/plyr.js#L3733, you can see that `isIphone` only has basic support. 

There are a bunch of other issues with plyr and iOS so the dev just let iOS handle its own controls in v2. You can tell if plyr is fully supported by calling `plyr.supported()` and then only add the listeners you need directly on the media element or embed API. More work for us, but I think the dev did that to keep plyr reliable and maintainable.

**Comment by sampotts** [comment]
Closing this one as I think it's fixed but feel free to re-open if not solved in v3 👍
