### ISSUE TITLE
What's wrong with this audio playlist

### ISSUE THREAD

**Issue by onigetoc** [sampotts/plyr#673]
Based on a old Plyr audio playlist on codepen.
https://codepen.io/jmisavage/pen/WwVQoB

I just upgraded to the last Plyr CDN and the new version is not working.
https://codepen.io/onigetoc/pen/OxmROo

**Comment by ducnv999** [comment]
add "radio = radio[0];" below "var radio = document.querySelector('.plyr').plyr;"

**Comment by onigetoc** [comment]
Hi @ducnv999 
it do nothing

**Comment by friday** [comment]
I'm closing this, since this is a support question for what's now an outdated version. The error you got looks like one that has been fixed. If you still need help, please upgrade to the latest version, simplify the code example to make it easier for us to understand it and go to our [slack channel](https://bit.ly/plyr-chat).
