### ISSUE TITLE
failed to execute 'play' on 'htmlmediaelement': api can only be initiated by a user gesture.

### ISSUE THREAD

**Issue by gurupras** [sampotts/plyr#716]
This is more of a question than a bug.

I have a webapp that attempts to synchronize media playback across multiple clients. This *requires* me to be able to play/pause for a remote client when any of the clients performs an action. All of this was working until recently, but now calling `plyrInstance.play()` throws the following error: `failed to execute 'play' on 'htmlmediaelement': api can only be initiated by a user gesture.`

- [x] Issue does not already exist
- [ ] Issue observed on https://plyr.io

### Expected behaviour 
Ability to control media playback purely via API without requiring user actions

### Actual behaviour
Chrome on Android (and iOS?) throws an error as described above if the API call did not originate from a user gesture
### Environment

- Browser: Chrome
- Version:  62.0.3202.84
- Operating System: Android
- Version: 7.1.2

Players affected:
- [x] HTML5 Video
- [x] HTML5 Audio
- [x] YouTube
- [x] Vimeo

### Steps to reproduce 
- Visit https://twoseven.xyz/#!/test-room on mobile
- Play video (will fail)
- Look at logs to find the error mentioned above

What is happening behind the scenes is the following:
  - On gesture, client sends server signal requesting play/pause
  - Server broadcasts the request to everyone in room
  - Client attempts to play/pause when it receives message from server
    - Fails with the aforementioned error

All of the above work just fine on desktops.

**Comment by friday** [comment]
That's because many mobile browsers don't permit autoplay. In particular with audio, as it's seen as intrusive. It has nothing to do with plyr, and it's not possible to circumvent unless you remove or mute the audio. The behavior is being adopted by desktop browsers too.

Related links:
https://developers.google.com/web/updates/2016/07/autoplay
https://www.macrumors.com/2017/09/19/safari-11-released-macos-sierra-os-x-el-capitan/
https://venturebeat.com/2017/09/14/chrome-will-no-longer-autoplay-content-with-sound-in-january-2018/

**Comment by sampotts** [comment]
Not sure there's a lot that can be done about this one?

**Comment by friday** [comment]
The only possible thing would be to document this if you haven't already.

**Comment by friday** [comment]
Closing since this is a browser feature/bug we can't do anything about.
