### ISSUE TITLE
Volume slider is displayed even if  no audio stream is available

### ISSUE THREAD

**Issue by omitech** [sampotts/plyr#719]
- [ ] Issue does not already exist
- [ ] Issue observed on https://plyr.io

### Expected behaviour 
No volume control (or volume control disabled) if video has no audio stream

### Actual behaviour
Volume control still present even if there is no audio stream in the video container (video stream only). Native chrome html5 video player does not show volume slider for such files. Although I'm not sure whether that is possible to detect via javascript.

### Environment

- Browser:
- Version:  
- Operating System:
- Version: 

Players affected:
- [x] HTML5 Video
- [ ] HTML5 Audio
- [ ] YouTube
- [ ] Vimeo

### Steps to reproduce 
- any video file without audio stream (only video)

**Comment by sampotts** [comment]
This will be fixed in v3. The only downer is that the volume controls will briefly show as of course I need to check if the media has audio tracks and that can only be done after the `loadeddata` event has occurred. I assume that most video will have audio so the default is for them to be shown. In the majority of cases `loadeddata` fires pretty quickly anyway.

**Comment by sampotts** [comment]
Closing this one as I think it's fixed but feel free to re-open if not solved in v3 👍

**Comment by LukasKalbertodt** [comment]
@sampotts  I think this is not yet resolved or has regressed. See this minimal example with 3.6.8: https://jsfiddle.net/7gpxm3oc/
The video used there only has one video track and no audio tracks. Yet, the audio controls stay enabled.
