### ISSUE TITLE
Logo Through Css

### ISSUE THREAD

**Issue by vibhi19** [sampotts/plyr#724]
Hi I used CSS to put logo But it get hidden as control hide is There any way I can make it always show 
here is the css which i use 

```
.plyr__controls {
 background:url(/wp/wp-content/uploads/bank.jpg) 99% 70% no-repeat,linear-gradient(rgba(0,0,0,0),rgba(0,0,0,.5))!important;
 background-size:100px auto,auto!important
}
```

and Im Thinking about If you can add Youtube lite embed Feature In Your development It can help Load Player very quikly

**Comment by friday** [comment]
`.plyr__controls` **is** the controls. If you don't want your logo to hide as the controls hide, you should add it to another element.

Btw, github issues are not for coding help/support. It's for posting about bugs, flaws, feature requests etc that benefits the community.

**Comment by vibhi19** [comment]
Thanks 
Well I also ask For youtube lite Embed support in player

**Comment by vibhi19** [comment]
and Please Let me Know if they have any group for asking These type of questions

**Comment by friday** [comment]
If you're referring to using https://github.com/TjWallas/YouTube-Lite-Embed, that's not a good candidate for plyr (very old, not updated in 4 years and requires jQuery). The performance benefit claim is also referencing the load time for youtube using flash, which modern browsers (IE9+) don't do. The same benefits wouldn't apply today. Even besides flash, lots of things has changed since, such as browser performance optimizations and HTTP2.

It's also an implementation detail rather than a feature suggestion, so if some of the performance benefits would still apply there are better ways to implement the optimizations without getting the downsides of the library.

**Comment by vibhi19** [comment]
well i dont ask for that library support i use that word To make you guys understand that to add lazy load in plyr so video can be load much faster
