### ISSUE TITLE
can we add custom button on audio/video controls to implement any add-on funtionality?

### ISSUE THREAD

**Issue by suvamkundu** [sampotts/plyr#787]
- [ ] Issue does not already exist
- [ ] Issue observed on https://plyr.io

### Environment

- Browser:
- Version:  
- Operating System:
- Version: 

Players affected:
- [ ] HTML5 Video
- [ ] HTML5 Audio
- [ ] YouTube
- [ ] Vimeo

### Steps to reproduce 
-

**Comment by friday** [comment]
I think this should be a discussion, rather than suggestion/idea.

It's very hard to design APIs for this type of extensibility, because different users want to add different things, with various degrees of complexity, yet still want the API to be simple. Settling for one type of implementation excludes others.

Meanwhile: You can add it by manipulating the dom after loading plyr.

**Comment by friday** [comment]
Closing in favor of #1047 (which is more specific).
