### ISSUE TITLE
RequireJS and Plyr

### ISSUE THREAD

**Issue by jonnitto** [sampotts/plyr#879]
If I use RequireJS and Plyr, I didn't receive the Plyr instance:

## Example: (Lock at the console output)

https://s.codepen.io/jonnitto/debug/zWeGjz/LQkExPzbXpYA

```html
<script src='https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.5/require.js'></script>
<script >
require(["https://cdn.plyr.io/3.1.0/plyr.js"], function () {
  console.log('3.1.0', arguments);
});

require(["https://cdn.plyr.io/2.0.18/plyr.js"], function () {
  console.log('2.0.18', arguments);
});
</script>
```

**Comment by jonnitto** [comment]
I still have to figure it out. I‘ve to support our old UI in the Neos Plugin. I think the post @friday made will help, but I can‘t use the code 1:1. I‘ll close this issue as soon as I have a solution.

**Comment by friday** [comment]
I'm also not that well acquainted with require.js. I tried searching for "RequireJS external named modules" for example, but with no luck. This strikes me as a pretty basic use case, but still nothing. If requirejs still has a decent number of users out there, you could probably find help on stackoverflow and similar places.

This should work too:

```js
require(["https://cdn.plyr.io/3.1.0/plyr.js"], function () {
  require(["Plyr"], function () {
    console.log('3.1.0', arguments);
  });
});
```

Feels like a hack rather than a solution though.

**Comment by jonnitto** [comment]
I found the same solution. Released Plyr 3 for Neos.io: https://github.com/jonnitto/Jonnitto.Plyr and https://github.com/jonnitto/Jonnitto.TextWithPlyr
