### ISSUE TITLE
setting Plyr variable when importing or requiring causes plyr object to not emit with events

### ISSUE THREAD

**Issue by jwjcmw** [sampotts/plyr#926]
**Edit...leaving this here for posterity, but this is not the issue...scroll to the end for the actual issue...also, title was changed to reflect actual issue**

I'm not sure if this is an issue with plyr, exactly...but I wanted others to be aware of it.  If you are using plyr through npm, and you pull it in through a ES6 import, like is done in this example:

https://codesandbox.io/s/887zvvpxl8

then the plyr object is available on events through event.detail.plyr, as stated in the documentation.  However if you do a node require to pull it in, as shown in this example:

https://codesandbox.io/s/1yn2mkx3vq

then the event.detail.plyr object is null.

Edit: just noticed the examples only work in chrome...not sure if that is my code or codesandbox, which I just started using.

**Comment by friday** [comment]
Neither worked in my tests. Anyway, this isn't related to npm or node.js. Your bundler (parcel.js) converts your import/require statements into bundled code, so if there is an issue there, it's because of parcel.js, codesandbox or their dependencies. However, it would be very strange if this somehow caused an error just to this part of the code, rather than crashing things completely.

**Comment by jwjcmw** [comment]
I actually came across this in another project which is webpack based...I just was trying to use codesandbox as a demonstration...did you view it in chrome?  It is just that part of the code which doesn't work...everything else seems to, which is very strange.  I guessing this is something with babel.

**Comment by friday** [comment]
Yes, in Chrome 65 everything worked apart from event.detail.plyr for me.

Babel seems more likely to be the culprit imo. In particular if the CustomEvent polyfill differs in some significant way. I'm not getting this in my local setup with the normal non-minified build with buble, brunch and polyfills.io.

Thanks for the info so far!

**Comment by jwjcmw** [comment]
OK, so I figured this out...what you don't want to do is set a variable like this:
`const Plyr = require("plyr");`
because then when plyr is checking the type of the plyr object when returning the event (lines 605 and 14 of utils.js) using "window.Plyr", it returns null.  
It actually fails with both the import or the require...the key was the variable name.  It looks like that is the only place that type check (is.plyr) is used, so that was the only thing that was failing.  I don't see any other references to window.Plyr in the plyr code.

**Comment by jwjcmw** [comment]
Edited title and first post to reflect actual issue...closing now.

**Comment by friday** [comment]
No need to close though (sorry if I scared you into it). It's a valid issue and very well described now. :)

The `utils.is.plyr`-method uses  `window.plyr` internally, which breaks `event.detail.plyr` when using loading Plyr as a module rather than global.

It's not as straightforward to solve as it might seem unfortunately, as the plyr class isn't available in that scope. Might have to resort to duck typing, or using es6-symbols (overkill imo). Either way I'll leave it for @sampotts to decide.
