### ISSUE TITLE
Captions on hls.js

### ISSUE THREAD

**Issue by indiecore-fm** [sampotts/plyr#971]
I noticed that plyr supports hls.js. This is great! Now looking at hls.js I see that they support 608 captioning. 

I run a deaf video platform and we are looking for a open source video player to get out of using JW. 

Anyone have any guidance on how to use the caption features from hls.js with plyr? On the actual hls.js example it loads and plays the captions automatically for my stream.

I see the example here: https://codepen.io/sampotts/pen/JKEMqB But don't see how to add captions in.

**Comment by friday** [comment]
You can add vtt captions as html5 tracks (which hls.js ignores) for Plyr. That's your only option for now.

**Comment by sampotts** [comment]
How do you normally set the captions with a HLS stream? We could easily add a setter to set the captions but I'm unfamiliar with the format they are usually set using HLS.

**Comment by friday** [comment]
You get the current index:
```
hls.subtitleTrack
```
(will be `-1` if no track is selected)

You get the list via:

```
hls.subtitleTracks
```

Which will output something like:

```
[
  {
    "groupId": "subtitles",
    "name": "Swedish",
    "type": "SUBTITLES",
    "default": false,
    "autoselect": false,
    "forced": false,
    "url": "sv.m3u8",
    "lang": "sv",
    "id": 0,
    "details": {
      "type": "VOD",
      "version": 3,
      "url": "sv.m3u8",
      "fragments": [
        {
          "_url": "sv.vtt",
          "_byteRange": null,
          "_decryptdata": {
            "method": null,
            "key": null,
            "iv": null,
            "_uri": null
          },
          "tagList": [
            [
              "INF",
              "86400.0"
            ]
          ],
          "_elementaryStreams": {
            "audio": false,
            "video": false
          },
          "duration": 86400,
          "title": null,
          "type": "subtitle",
          "start": 0,
          "levelkey": {
            "method": null,
            "key": null,
            "iv": null,
            "_uri": null
          },
          "sn": 1,
          "level": 0,
          "cc": 0,
          "baseurl": "sv.m3u8",
          "relurl": "sv.vtt",
          "trackId": 0,
          "loaded": 55
        }
      ],
      "live": false,
      "startSN": 1,
      "targetduration": 86400,
      "totalduration": 86400,
      "averagetargetduration": 86400,
      "endSN": 1,
      "startCC": 0,
      "endCC": 0,
      "tload": 4991.900000022724
    }
  },
  {
    "groupId": "subtitles",
    "name": "English",
    "type": "SUBTITLES",
    "default": false,
    "autoselect": false,
    "forced": false,
    "url": "en.m3u8",
    "lang": "en",
    "id": 1
  }
]
```

As you can see, the first track contains more info (mostly irrelevant for us) because it's loaded, while the second isn't. It doesn't seem like you can get the actual cues from either, and you can only get the vtt link once the manifest (m3u8) has been parsed.

For the selected track only you can get the cues via `video.TextTracks` (like html, since hls.js uses native html5 cues). That would be `document.querySelector('video').textTracks[hls.subtitleTrack].cues` (provided hls.subtitleTrack isn't -1).

You'd then think setting `hls.subtitleTrack` would work as well, but [it doesn't seem to be the case](https://github.com/video-dev/hls.js/issues/1184) (and my tests confirms this).

So overall not too easy. We would have to get the manifests (ex `en.m3u8` ^, then parse them, get the caption files and parse them). Both m3u8 and vtt are pretty simple to parse. I don't know about other formats though.

**Comment by indiecore-fm** [comment]
We have always used 608 for live streaming so it works on any device. It also has it built in to the video itself so we don’t have to worry about a sidecar file. 

It’s also what’s protected currently from the ADA. 

We use wowza. So you’re saying we can send vtt captions inside an live hls stream?

For on demand files we can easily load a side VTT. But using one for a live stream escapes me. So we have always relied on 608.

**Comment by friday** [comment]
Dug a bit deeper, and found that setting `hls.subtitleTrack`, even if it doesn't fully work for setting the caption track, at least loads the resource and adds the cues to the track. So we don't have to parse anything. Should have picked that up by reading the issue really.

Running this after setting `hls.subtitleTrack` fixes the rest in my tests:
```js
Array.prototype.forEach.call(hls.media.textTracks, function (track, index) {
	track.mode = (index === hls.subtitleTrack) ? 'showing' : 'hidden';
});
```

If you wait for the `Hls.Events.MANIFEST_LOADED` (not `Hls.Events.MANIFEST_PARSED`) event in hls.js before initiating Plyr, then the textTracks will be set, and as a result the track selection menu will be correctly generated by Plyr (this means you can't use the method in #957).

However, switching will only work if hls.js has loaded each track first. If you initially load hls.js and not Plyr, switch some tracks via the native browser controls or setting `hls.subtitleTrack` and then load Plyr it will work (for the tracks you loaded).

All of this was using pre-rendered manifests and VTT. I don't have the environment for live streaming and 608 captions and don't know much about it. But I imagine if we can support Hls.js vtt caption we will at least be one step closer to 608 captions as well.

I think the first step would be finding out why setting `hls.subtitleTrack` doesn't work after loading Plyr, and fixing this. Currently it loads the file, and sets the TextTrack's `cues` property to a an empty `TextTrackCueList`, while if we do it before loading Plyr the list won't be empty.

If we fix this, then pass the track index in the `languagechange` event, this event could be used for setting `hls.subtitleTrack`.

Contributions are welcome.

**Comment by friday** [comment]
@indiecore-fm I found a sample hls manifest with embedded subtitles (don't know which format), and updated the code sample ^ to cover both vtt and embedded. The sample above should work for you now, hopefully. Circumstances are not optimal though.

Improvements Plyr could do:
* Trigger `languagechange` when the language is initially set
* Keep internal reference to track index rather than just language code (which may not be unique).
* Handle textTracks added to the media after loading Plyr (this would break the other method with html5 tracks, so it should wait until all bases are covered imo).

The rest are all hls.js issues.

**Comment by friday** [comment]
Plyr v3.3.10 solves most of this.

Example implementation:
http://jsbin.com/larecojihe/1/edit?js,output

Hls.js still has some issues on their side. We can avoid some of the worst now since we no longer have to trust their events.

Further improvements Plyr could do:
* Keep internal reference to track index rather than just language code (which may not be unique).

**Comment by friday** [comment]
Closing in favor of #994

**Comment by indiecore-fm** [comment]
<3
